
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 05 22:42:00 COT 2021
//----------------------------------------------------

package analizadorSin;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinPara = 29;
  public static final int Si = 11;
  public static final int Op_log = 7;
  public static final int Numero = 2;
  public static final int Leer = 9;
  public static final int Entero = 12;
  public static final int Mientras = 18;
  public static final int Para = 23;
  public static final int Identificador = 3;
  public static final int Programa = 15;
  public static final int FinMientras = 24;
  public static final int T_dato = 19;
  public static final int P_coma = 10;
  public static final int Sino = 28;
  public static final int Cadena = 17;
  public static final int Op_ar = 8;
  public static final int EOF = 0;
  public static final int Hacer = 26;
  public static final int FinPrograma = 14;
  public static final int Entonces = 21;
  public static final int Escribir = 20;
  public static final int FinSi = 22;
  public static final int P_izq = 4;
  public static final int error = 1;
  public static final int P_der = 5;
  public static final int Real = 25;
  public static final int Igual = 27;
  public static final int Hasta = 13;
  public static final int Op_rel = 6;
  public static final int Error = 16;
}

